/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.14.v202310241606.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/rccltest/RcclTestSomeIPStubAdapter.hpp>
#include <v1/rccltest/RcclTest.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace rccltest {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createRcclTestSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< RcclTestSomeIPStubAdapter<::v1::rccltest::RcclTestStub>>(_address, _connection, _stub);
}

void initializeRcclTestSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:rccltest.RcclTest:v1_0:RcclTest",
         0x1234, 0x5678, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "rccltest.RcclTest:v1_0",
        &createRcclTestSomeIPStubAdapter);
}

INITIALIZER(registerRcclTestSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeRcclTestSomeIPStubAdapter);
}

} // namespace rccltest
} // namespace v1
